
# Exercise 1.A NumPy: Manipulating Array

In [22]:
import numpy as np

## Looping Through Arrays

In [23]:
arrA = np.array([[11, 12, 13], [14, 15, 16]])
print(arrA)

[[11 12 13]
 [14 15 16]]


In [24]:
for x in arrA:
    print(x * 2)

[22 24 26]
[28 30 32]


In [25]:
for x in arrA:
    for y in x:
        print(y * 2)

22
24
26
28
30
32


The first loop goes through each row of the array and multiplies the whole row by 2
The second loop goes inside each row and multiplies each individual number by 2

In [26]:
for x in arrA:
    for y in x:
        loop_result = x * 2
        print(loop_result)

# This prints the whole row doubled each time because loop_result uses x * 2, not y * 2.

[22 24 26]
[22 24 26]
[22 24 26]
[28 30 32]
[28 30 32]
[28 30 32]


## Joining and Stacking Arrays

In [27]:
joined_array_1 = np.concatenate((arrA, arrA), axis=0)
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [28]:
joined_array_2 = np.concatenate((arrA,), axis=1)
print(joined_array_2)

[[11 12 13]
 [14 15 16]]


In [29]:
stacked_array_1 = np.stack((joined_array_1, joined_array_1))
print(stacked_array_1)

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [30]:
stacked_array_2 = np.stack((joined_array_1, joined_array_2))
print(stacked_array_2)
   
Error all input arrays must have same shape


SyntaxError: invalid syntax (3048640444.py, line 4)

In [ ]:
another_joined_array = np.concatenate((joined_array_1, arrA))
print(another_joined_array)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [ ]:
h_stack = np.hstack((arrA, arrA))  # joins arrays horizontally
v_stack = np.vstack((arrA, arrA))  # joins arrays vertically
d_stack = np.dstack((arrA, arrA))  # joins arrays by depth

print(h_stack)
print(v_stack)
print(d_stack)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]
[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]
[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


## Splitting Arrays

In [ ]:
splitsky = np.array_split(joined_array_1, 2)
print(splitsky)

# This breaks the array into 2 parts. Each part still has rows and columns.

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [ ]:
spliterino = np.array_split(joined_array_1, 3)
print(spliterino)

# This breaks the array into 3 smaller parts. Each part still has rows and columns, but some parts may be bigger than others.

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13]]), array([[14, 15, 16]])]


## Searching and Replacing Array Values

In [33]:
result_1 = np.where(arrA % 2 == 0, arrA, "odd")
print(result_1)

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


## Sorting and Filtering Arrays

In [35]:
arrB = np.array([[7, 6], [13, 5], [7, 3]])

arrB_sorted = np.sort(arrB)
print(arrB_sorted)

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [36]:
print(arrB)

z = arrB < 7
arrC = arrB[z]

print(arrC)

[[ 7  6]
 [13  5]
 [ 7  3]]
[6 5 3]


In [37]:
print(arrB)

y = arrB >= 7
arrD = arrB[y]

print(arrD)

[[ 7  6]
 [13  5]
 [ 7  3]]
[ 7 13  7]
