In [1]:
import numpy as np

## Generating Random Numbers

In [2]:
# Random integers from 1 to 20
r_1 = np.random.randint(1, 21, 2)

print(r_1)

[ 5 16]


In [3]:
# Random integers with 1 row and 2 columns
r_2 = np.random.randint(1, 21, (1, 2))

print(r_2)

[[17  8]]


In [4]:
# Random decimal numbers between 0 and 1
r_3 = np.random.random((2, 1))

print(r_3)

[[0.82753131]
 [0.98540811]]


In [5]:
# Random integers from 20 to 100
r_4 = np.random.randint(20, 101, (4, 5))

print(r_4)

[[76 60 94 21 87]
 [68 91 24 31 46]
 [86 65 22 85 44]
 [34 20 37 51 41]]


In [6]:
# Random decimal numbers between 0 and 1
r_5 = np.random.random((4, 5))

print(r_5)

[[0.61213481 0.85570431 0.07353612 0.69246193 0.11826179]
 [0.39489319 0.93293398 0.64676885 0.43403    0.54827122]
 [0.49678814 0.15304914 0.47272167 0.39628025 0.65070825]
 [0.58014473 0.73753726 0.44575058 0.55065885 0.35425693]]


## Generating Random Choices from an Array

In [7]:
# List of student names
students = np.array([
    "Alexus", "Blake,", "Corey", "Daniel",
    "Lorah", "Hana", "Louis", "mohamed",
    "Saliem", "Tihtina", "samia", "victoria"
])

print(students)

['Alexus' 'Blake,' 'Corey' 'Daniel' 'Lorah' 'Hana' 'Louis' 'mohamed'
 'Saliem' 'Tihtina' 'samia' 'victoria']


In [8]:
# Pick one random student
call_on = np.random.choice(students)

print(call_on)

Hana


In [9]:
# Create random breakout groups
breakout_groups = np.random.choice(students, (3, 4))

print(breakout_groups)

# This may not be  best way to make groups
# because some students can appear more than once.

[['Saliem' 'Tihtina' 'Daniel' 'Lorah']
 ['Blake,' 'Louis' 'Daniel' 'Alexus']
 ['mohamed' 'Blake,' 'samia' 'victoria']]


In [ ]:
# Pick 5 students with different chances
call_on_weighted = np.random.choice(
    students,
    5,
    p=[0.30, 0.10, 0.10, 0.10,
       0.05, 0.05, 0.05, 0.05,
       0.05, 0.05, 0.10, 0.00]
)

print(call_on_weighted)

# Alexus has a 30% chance of being picked.
# Victodia has a 0% chance, so they will not be picked.
# Blake has 10% chance of being picked.
# The other students have smaller chances.

## Generating a Normal Distribution

In [ ]:
# Create a normal distribution
bell_curve = np.random.normal(10, 5, (4, 5))

print(bell_curve)