In [6]:
import numpy as np

## Sample Arrays

In [8]:
# Random arrays to practice with

r_1 = np.random.randint(1, 21, 2)

r_2 = np.random.randint(1, 21, (1, 2))

r_3 = np.random.random((2, 1))

r_4 = np.random.randint(20, 101, (4, 5))

r_5 = np.random.random((4, 5))

print(r_1)
print(r_2)
print(r_3)
print(r_4)
print(r_5)

[10 19]
[[ 1 20]]
[[0.65554171]
 [0.10018782]]
[[54 26 36 44 53]
 [28 89 59 27 26]
 [74 28 40 28 28]
 [63 36 73 20 61]]
[[0.87704652 0.31275469 0.64789218 0.89908878 0.3540639 ]
 [0.56993974 0.32731543 0.92375493 0.7771511  0.57449501]
 [0.10811844 0.59706363 0.41095943 0.22929428 0.05207462]
 [0.3196605  0.10004123 0.0540019  0.57322145 0.87901637]]


## Permutations

In [9]:
# Print r_4 before shuffling
print(r_4)

[[54 26 36 44 53]
 [28 89 59 27 26]
 [74 28 40 28 28]
 [63 36 73 20 61]]


In [10]:
# Shuffle the rows in r_4
np.random.shuffle(r_4)

print(r_4)

[[74 28 40 28 28]
 [63 36 73 20 61]
 [28 89 59 27 26]
 [54 26 36 44 53]]


The shuffle function changes the order of the rows in the array.  
It also changes the original array itself.

In [11]:
# Create a shuffled copy
new_shuffle = np.random.permutation(r_4)

print(new_shuffle)

# Print r_4 again
print(r_4)

[[28 89 59 27 26]
 [74 28 40 28 28]
 [63 36 73 20 61]
 [54 26 36 44 53]]
[[74 28 40 28 28]
 [63 36 73 20 61]
 [28 89 59 27 26]
 [54 26 36 44 53]]


Shuffle changes the original array.  
Permutation makes a new shuffled copy and keeps the original array the same.

## Mathematical Operations

In [12]:
print(r_1)
print(r_2)

print(r_1.shape)
print(r_2.shape)

answer_1 = np.add(r_1, r_2)

print(answer_1)
print(answer_1.shape)

[10 19]
[[ 1 20]]
(2,)
(1, 2)
[[11 39]]
(1, 2)


In [ ]:
print(r_1)
print(r_3)

print(r_1.shape)
print(r_3.shape)

answer_2 = np.add(r_1, r_3)

print(answer_2)
print(answer_2.shape)

In [13]:
print(r_2)
print(r_4)

print(r_2.shape)
print(r_4.shape)

answer_3 = np.add(r_2, r_4)

print(answer_3)
print(answer_3.shape)

[[ 1 20]]
[[74 28 40 28 28]
 [63 36 73 20 61]
 [28 89 59 27 26]
 [54 26 36 44 53]]
(1, 2)
(4, 5)


ValueError: operands could not be broadcast together with shapes (1,2) (4,5) 

In [ ]:
# This gives an error because the array sizes do not match

print(np.add(r_1, r_4))

In [14]:
# Add [[1]] to every value in r_4
print(np.add(r_4, np.array([[1]])))

[[75 29 41 29 29]
 [64 37 74 21 62]
 [29 90 60 28 27]
 [55 27 37 45 54]]


In [15]:
# Add 1 to each column
print(np.add(r_4, np.array([1, 1, 1, 1, 1])))

[[75 29 41 29 29]
 [64 37 74 21 62]
 [29 90 60 28 27]
 [55 27 37 45 54]]


Broadcasting is how NumPy works with arrays of different sizes.
NumPy matches the shapes so math operations can work together.
The larger array usually decides the shape of the final result.

## Rounding

In [16]:
# Print r_3
print(r_3)

[[0.65554171]
 [0.10018782]]


In [17]:
# Remove decimal values
print(np.trunc(r_3))

[[0.]
 [0.]]


In [18]:
# Round toward zero
print(np.fix(r_3))

[[0.]
 [0.]]


In [19]:
# Round down
print(np.floor(r_3))

[[0.]
 [0.]]


In [20]:
# Round up
print(np.ceil(r_3))

[[1.]
 [1.]]


In [21]:
# Round to 2 decimal places
print(np.round(r_3, 2))

[[0.66]
 [0.1 ]]


## Cumulative Operations

In [22]:
print(r_4)

[[74 28 40 28 28]
 [63 36 73 20 61]
 [28 89 59 27 26]
 [54 26 36 44 53]]


In [23]:
# Add all values
print(np.sum(r_4))

893


In [24]:
# Add values down the columns
print(np.sum(r_4, axis=0))

[219 179 208 119 168]


In [25]:
# Add values across the rows
print(np.sum(r_4, axis=1))

[198 253 229 213]


In [26]:
# Rolling total
print(np.cumsum(r_4))

[ 74 102 142 170 198 261 297 370 390 451 479 568 627 654 680 734 760 796
 840 893]


In [27]:
# Rolling total down the columns
print(np.cumsum(r_4, axis=0))

[[ 74  28  40  28  28]
 [137  64 113  48  89]
 [165 153 172  75 115]
 [219 179 208 119 168]]


## Grocery Problem

In [28]:
# vegetables, fruits, snacks, beverages

bag1 = np.array([2, 3, 4, 0])

bag2 = np.array([4, 0, 1, 2])

print(bag1)
print(bag2)

[2 3 4 0]
[4 0 1 2]


In [29]:
# Total items in each bag

total1 = np.sum(bag1)
total2 = np.sum(bag2)

print("The first bag contains", total1, "items.")
print("The second bag contains", total2, "items.")

The first bag contains 9 items.
The second bag contains 7 items.


In [30]:
# Total items in each category

totals = bag1 + bag2

print("There are", totals[0], "vegetables,", 
      totals[1], "fruits,", 
      totals[2], "boxes of snacks, and", 
      totals[3], "beverages.")

There are 6 vegetables, 3 fruits, 5 boxes of snacks, and 2 beverages.


## Teamwork

In [31]:
# Ali's data
ali = np.array([5, 4, 6, 4, 2])

print(ali)

[5 4 6 4 2]


In [32]:
# Ben's data
ben = np.array([0, 5, 5, 3, 4])

print(ben)

[0 5 5 3 4]


In [33]:
# Carla's data
carla = np.array([3, 6, 0, 3, 4])

print(carla)

[3 6 0 3 4]


In [34]:
# Put all data together

all_knocks = np.array([ali, ben, carla])

print(all_knocks)

[[5 4 6 4 2]
 [0 5 5 3 4]
 [3 6 0 3 4]]


In [35]:
# Weekly totals

print("Ali knocked on", np.sum(ali), "doors.")
print("Ben knocked on", np.sum(ben), "doors.")
print("Carla knocked on", np.sum(carla), "doors.")

print("The group knocked on", np.sum(all_knocks), "doors total.")

Ali knocked on 21 doors.
Ben knocked on 17 doors.
Carla knocked on 16 doors.
The group knocked on 54 doors total.


In [36]:
# Daily totals
daily_total = np.sum(all_knocks, axis=0)

# Rolling total
rolling_total = np.cumsum(daily_total)

# Estimated votes
estimated_votes = rolling_total * 0.5

print(estimated_votes)

[ 4.  11.5 17.  22.  27. ]
